#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TinderBay.Resource", IsApplication=true)]

namespace TinderBay
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060000
			public const int tagArray = 2131099648;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int bike = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int bucket1 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int car = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int five = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int four = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int fryingpan = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Icon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int one = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Pencil = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int shoe1 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int six = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int three = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int two = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int userLoginEtxtBackground = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int zero = 2130837518;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070038
			public const int TagSelectSpinner = 2131165240;
			
			// aapt resource value: 0x7f070000
			public const int actionMenuView = 2131165184;
			
			// aapt resource value: 0x7f070028
			public const int btnBuy = 2131165224;
			
			// aapt resource value: 0x7f07003e
			public const int btnConfirm = 2131165246;
			
			// aapt resource value: 0x7f070035
			public const int btnHistory = 2131165237;
			
			// aapt resource value: 0x7f07002e
			public const int btnLogin = 2131165230;
			
			// aapt resource value: 0x7f070037
			public const int btnLogout = 2131165239;
			
			// aapt resource value: 0x7f070036
			public const int btnSale = 2131165238;
			
			// aapt resource value: 0x7f07002f
			public const int btnSignup = 2131165231;
			
			// aapt resource value: 0x7f070002
			public const int btnToAccount = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int btnToHome = 2131165185;
			
			// aapt resource value: 0x7f070023
			public const int btnToSearch = 2131165219;
			
			// aapt resource value: 0x7f070034
			public const int btnUpdateEmail = 2131165236;
			
			// aapt resource value: 0x7f070033
			public const int btnUpdatePassword = 2131165235;
			
			// aapt resource value: 0x7f070022
			public const int button4 = 2131165218;
			
			// aapt resource value: 0x7f070003
			public const int buybutton = 2131165187;
			
			// aapt resource value: 0x7f07003a
			public const int displayText = 2131165242;
			
			// aapt resource value: 0x7f07003d
			public const int etxtConfirmPassword = 2131165245;
			
			// aapt resource value: 0x7f07002d
			public const int etxtPassword = 2131165229;
			
			// aapt resource value: 0x7f07002b
			public const int etxtUsername = 2131165227;
			
			// aapt resource value: 0x7f070008
			public const int gridLayout1 = 2131165192;
			
			// aapt resource value: 0x7f070024
			public const int imageView1 = 2131165220;
			
			// aapt resource value: 0x7f070030
			public const int imgbtnProfile = 2131165232;
			
			// aapt resource value: 0x7f070005
			public const int linearLayout1 = 2131165189;
			
			// aapt resource value: 0x7f070018
			public const int linearLayout10 = 2131165208;
			
			// aapt resource value: 0x7f07001b
			public const int linearLayout11 = 2131165211;
			
			// aapt resource value: 0x7f07001e
			public const int linearLayout12 = 2131165214;
			
			// aapt resource value: 0x7f07001f
			public const int linearLayout13 = 2131165215;
			
			// aapt resource value: 0x7f070025
			public const int linearLayout2 = 2131165221;
			
			// aapt resource value: 0x7f070009
			public const int linearLayout4 = 2131165193;
			
			// aapt resource value: 0x7f07000c
			public const int linearLayout5 = 2131165196;
			
			// aapt resource value: 0x7f07000f
			public const int linearLayout6 = 2131165199;
			
			// aapt resource value: 0x7f070012
			public const int linearLayout7 = 2131165202;
			
			// aapt resource value: 0x7f070015
			public const int linearLayout8 = 2131165205;
			
			// aapt resource value: 0x7f070027
			public const int priceView = 2131165223;
			
			// aapt resource value: 0x7f070026
			public const int productNameView = 2131165222;
			
			// aapt resource value: 0x7f070004
			public const int relativeLayout1 = 2131165188;
			
			// aapt resource value: 0x7f070039
			public const int returnBtn = 2131165241;
			
			// aapt resource value: 0x7f07000b
			public const int textView12 = 2131165195;
			
			// aapt resource value: 0x7f07000e
			public const int textView13 = 2131165198;
			
			// aapt resource value: 0x7f070011
			public const int textView14 = 2131165201;
			
			// aapt resource value: 0x7f070014
			public const int textView15 = 2131165204;
			
			// aapt resource value: 0x7f070017
			public const int textView16 = 2131165207;
			
			// aapt resource value: 0x7f07001a
			public const int textView17 = 2131165210;
			
			// aapt resource value: 0x7f07001d
			public const int textView18 = 2131165213;
			
			// aapt resource value: 0x7f070021
			public const int textView19 = 2131165217;
			
			// aapt resource value: 0x7f070006
			public const int textView4 = 2131165190;
			
			// aapt resource value: 0x7f070019
			public const int view10 = 2131165209;
			
			// aapt resource value: 0x7f07001c
			public const int view11 = 2131165212;
			
			// aapt resource value: 0x7f070020
			public const int view12 = 2131165216;
			
			// aapt resource value: 0x7f070007
			public const int view2 = 2131165191;
			
			// aapt resource value: 0x7f07000a
			public const int view5 = 2131165194;
			
			// aapt resource value: 0x7f07000d
			public const int view6 = 2131165197;
			
			// aapt resource value: 0x7f070010
			public const int view7 = 2131165200;
			
			// aapt resource value: 0x7f070013
			public const int view8 = 2131165203;
			
			// aapt resource value: 0x7f070016
			public const int view9 = 2131165206;
			
			// aapt resource value: 0x7f07003c
			public const int vtxtConfirmPassword = 2131165244;
			
			// aapt resource value: 0x7f070031
			public const int vtxtEmail = 2131165233;
			
			// aapt resource value: 0x7f070032
			public const int vtxtItemSale = 2131165234;
			
			// aapt resource value: 0x7f070029
			public const int vtxtLogin = 2131165225;
			
			// aapt resource value: 0x7f07002c
			public const int vtxtPassword = 2131165228;
			
			// aapt resource value: 0x7f07003b
			public const int vtxtSignup = 2131165243;
			
			// aapt resource value: 0x7f07002a
			public const int vtxtUsername = 2131165226;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int CheckoutLayout = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int HistoryLayout = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int HomeLayout = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int Main = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int ProfileLayout = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int SearchLayout = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int SearchResultLayout = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int SignupLayout = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int UpdatePasswordLayout = 2130968584;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
